### ISSUE TITLE
Latest nightly fails compiling r-efi (unknown feature 'const_int_ops')

### ISSUE THREAD

**Issue by Richard-W** [r-util/r-efi#5]
```
 Compiling r-efi v0.1.1
error[E0635]: unknown feature `const_int_ops`
```

I know this is fixed on master but the fix is not published on crates.io. Can you publish a new release? Depending on the git repository is not a long-term solution.

**Comment by dvdhrm** [comment]
I bumped the major version and pushed to crates.io. Thanks for the hint!

**Comment by Richard-W** [comment]
Thanks a lot!
